services:
  backend:
    build: ./backend
    container_name: mern-backend-c1
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    env_file:
      - ./backend/.env  
  frontend:
    build: ./frontend
    container_name: mern-frontend-c1
    ports:
      - '3000:3000'
    volumes:
    - ./frontend:/frontend
    - /frontend/node_modules
    stdin_open: true
    tty: true
